//Loading
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

//Login.js
export const LOGIN = 'LOGIN';
export const RECEIVE_LOGIN_RESULT = 'RECEIVE_LOGIN_RESULT';

//auth
export const SIGNUP = 'SIGNUP';
export const RECEIVE_SIGNUP_RESULT = 'RECEIVE_SIGNUP_RESULT';
export const GET_INIT_DATA = 'GET_INIT_DATA';
export const INIT_DATA_SUCCESSS = 'INIT_DATA_SUCCESSS';

// article.js
export const RECEIVE_ARTICLE_LIST_RESULT = 'RECEIVE_ARTICLE_LIST_RESULT';
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';
export const RECEIVE_ARTICLE_BY_ID_RESULT = 'RECEIVE_ARTICLE_BY_ID_RESULT';
export const GET_ARTICLE_BY_ID = 'GET_ARTICLE_BY_ID';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const RECEIVE_CREATE_ARTICLE_RESULT = 'RECEIVE_CREATE_ARTICLE_RESULT';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_RESULT = 'DELETE_ARTICLE_RESULT';

// material.js
export const GET_MATERIAL_LIST = 'GET_MATERIAL_LIST';
export const RECEIVE_MATERIAL_LIST = 'RECEIVE_MATERIAL_LIST';