//Loading
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

//Login.js
export const LOGIN = 'LOGIN';
export const RECEIVE_LOGIN_RESULT = 'RECEIVE_LOGIN_RESULT';

//auth
export const SIGNUP = 'SIGNUP';
export const RECEIVE_SIGNUP_RESULT = 'RECEIVE_SIGNUP_RESULT';

// article.js
export const RECEIVE_ARTICLE_LIST_RESULT = 'RECEIVE_ARTICLE_LIST_RESULT';
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';
export const RECEIVE_ARTICLE_BY_ID_RESULT = 'RECEIVE_ARTICLE_BY_ID_RESULT';
export const GET_ARTICLE_BY_ID = 'GET_ARTICLE_BY_ID';