//Loading
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

//auth
export const GET_INIT_DATA = 'GET_INIT_DATA';
export const INIT_DATA_SUCCESSS = 'INIT_DATA_SUCCESSS';

export const GET_DISTRIBUTORS = 'GET_DISTRIBUTORS';
export const RECEIVE_DISTRIBUTORS = 'RECEIVE_DISTRIBUTORS';
export const RECEIVE_CUSTOMERS = 'RECEIVE_CUSTOMERS';
export const TOGGLE_SELECT_CUSTOMER_MODAL = 'TOGGLE_SELECT_CUSTOMER_MODAL';

export const SELECT_CUSTOMER = 'SELECT_CUSTOMER';
export const SELECT_DISTRIBUTORS_STOPS = 'SELECT_DISTRIBUTORS_STOPS';
export const CHECK_CUSTOMER_DB_STATUS = 'CHECK_CUSTOMER_DB_STATUS';
export const GET_CUSTOMER_DISTRIBUTORS = 'GET_CUSTOMER_DISTRIBUTORS';
export const RECEIVE_DISTRIBUTORS_STOPS = 'RECEIVE_DISTRIBUTORS_STOPS';
export const RECEIVE_ADS = 'RECEIVE_ADS';
export const GET_CUSTOMERS_USERS_ROLES = 'GET_CUSTOMERS_USERS_ROLES';
export const RECEIVE_CUSTOMERS_USERS_ROLES = 'RECEIVE_CUSTOMERS_USERS_ROLES';
export const SET_CUSTOMERS_USERS_ROLES = 'SET_CUSTOMERS_USERS_ROLES';
export const SET_CUSTOMERS_USERS_ROLES_RESULT = 'SET_CUSTOMERS_USERS_ROLES_RESULT';
export const SET_PAYLINKINFO = 'SET_PAYLINKINFO';
export const SET_PAYLINKINFO_RESULT = 'SET_PAYLINKINFO_RESULT';

//Search Result
export const SEARCH_ALL = 'SEARCH_ALL';
export const RECEIVE_SEARCH_RESULT = 'RECEIVE_SEARCH_RESULT';




export const HIDE_EMAIL_MODAL = 'HIDE_EMAIL_MODAL';
export const RESET_SIGN_UP_MESSAGE = 'RESET_SIGN_UP_MESSAGE';
//For Login
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_COMPLETED = 'LOGOUT_COMPLETED';
export const RECEIVE_LOGIN_RESULT = 'RECEIVE_LOGIN_RESULT';
// export const RECEIVE_VERIFY_SESSION_RESULT = 'RECEIVE_VERIFY_SESSION_RESULT';
export const SENDNEWUSERCREATE = 'SENDNEWUSERCREATE';
export const SENDPASSWORDRESET = 'SENDPASSWORDRESET';
export const RECEIVE_PASSWORD_RESET_RESULT = 'RECEIVE_PASSWORD_RESET_RESULT';
export const RECEIVE_USER_CREATE_RESULT_FAIL = 'RECEIVE_USER_CREATE_RESULT_FAIL';
export const RECEIVE_USER_CREATE_RESULT_SUCCESS = 'RECEIVE_USER_CREATE_RESULT_SUCCESS';
export const LOGIN_NO_NETWORK = 'LOGIN_NO_NETWORK';
export const SIGNUP_NO_NETWORK = 'SIGNUP_NO_NETWORK';
export const RESET_NO_NETWORK = 'RESET_NO_NETWORK';
export const RESET_MESSAGE = 'RESET_MESSAGE';

//Search Product
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const PRESS_FILTERSPEC = 'PRESS_FILTERSPEC';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_ALPHA = 'CHANGE_ALPHA';
export const GET_BRANDS = 'GET_BRANDS';
export const QUERY_BRANDS = 'QUERY_BRANDS';
export const RECEIVE_BRANDS_RESULT = 'RECEIVE_BRANDS_RESULT';
export const RESET_FILTER = 'RESET_FILTER';
export const FILTER_BRANDS = 'FILTER_BRANDS';
export const HIDDEN_FILTER_CONTENT = 'HIDDEN_FILTER_CONTENT';
export const SET_PRICE = 'SET_PRICE';
export const SET_ABV = 'SET_ABV';
export const RESET_PRICE = 'RESET_PRICE';
export const RECEIVE_PRODUCT_FROM_ANALYSIS = 'RECEIVE_PRODUCT_FROM_ANALYSIS';

//Products
export const QUERY_PRODUCTS = 'QUERY_PRODUCTS';
export const QUERY_PRODUCTS_BY_AD = 'QUERY_PRODUCTS_BY_AD';
export const RECEIVE_PRODUCTS_RESULT = 'RECEIVE_PRODUCTS_RESULT';


export const GET_RECENT_ORDERS_FROM_DISTRIBUTOR = 'GET_RECENT_ORDERS_FROM_DISTRIBUTOR';
export const CANCEL_RECENT_ORDERS_FROM_DISTRIBUTOR = 'CANCEL_RECENT_ORDERS_FROM_DISTRIBUTOR';

// export const RECEIVE_RECENT_ORDERS_FROM_DISTRIBUTOR = 'RECEIVE_RECENT_ORDERS_FROM_DISTRIBUTOR';
export const RECEIVE_PLACED_ORDERS = 'RECEIVE_PLACED_ORDERS';
export const GET_MY_ORDERS_FROM_DISTRIBUTOR = 'GET_MY_ORDERS_FROM_DISTRIBUTOR';
export const GET_MY_ORDER_TRANS_FROM_DISTRIBUTOR = 'GET_MY_ORDER_TRANS_FROM_DISTRIBUTOR';
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
export const RECEIVE_ORDER_TRANS = 'RECEIVE_ORDER_TRANS';
export const RESET_BACK_RESULTS = 'RESET_BACK_RESULTS';

export const GET_PURCHASED_PRODUCTS = 'GET_PURCHASED_PRODUCTS';


//Acount Information
export const ADD_A_CUSTOMER = 'ADD_A_CUSTOMER';

export const RECEIVE_CREATE_CUSTOMER_ERROR = 'RECEIVE_CREATE_CUSTOMER_ERROR';
export const RECEIVE_CREATE_CUSTOMER_SUCCESS = 'RECEIVE_CREATE_CUSTOMER_SUCCESS';
export const SET_ISADDINGCUSTOMER_TRUE = 'SET_ISADDINGCUSTOMER_TRUE';

export const RESET_ADD_SHOP = 'RESET_ADD_SHOP';

export const AUTO_LINK_CUSTOMERS = 'AUTO_LINK_CUSTOMERS';
export const AUTO_LINK_CUSTOMERS_RESULTS = 'AUTO_LINK_CUSTOMERS_RESULTS';
export const UPLOADDBANDLOG = 'UPLOADDBANDLOG';
export const UPLOADDBANDLOG_DONE = 'UPLOADDBANDLOG_DONE';


export const CHANGE_ADD_STATUS = 'CHANGE_ADD_STATUS';


//Acount Info Attributes
export const GET_ACCOUNT_INFO_ATTRIBUTES = 'GET_ACCOUNT_INFO_ATTRIBUTES';
export const SET_ACCOUNT_INFO_ATTRIBUTES = 'SET_ACCOUNT_INFO_ATTRIBUTES';

//Invoice
export const INIT_INVOICE_EDIT_DATA = 'INIT_INVOICE_EDIT_DATA';
export const RECEIVE_INVOICE_EDIT_DATA = 'RECEIVE_INVOICE_EDIT_DATA';
export const RECEIVE_INVOICE_TRANS = 'RECEIVE_INVOICE_TRANS';

export const ADD_INVOICE_TRANS = 'ADD_INVOICE_TRANS';
export const EDIT_INVOICE_TRANS = 'EDIT_INVOICE_TRANS';

export const ADD_PRODUCT_TRANS = 'ADD_PRODUCT_TRANS';
export const RECEIVE_ADD_PRODUCT_TRANS = 'RECEIVE_ADD_PRODUCT_TRANS';

export const SEARCH_BUY_LIST = 'SEARCH_BUY_LIST';
export const REFRESH_DISPLAYTRANS = 'REFRESH_DISPLAYTRANS';

export const SYNC_ORDER_TO_SERVER = 'SYNC_ORDER_TO_SERVER';
export const PLACE_IN_ORDER = 'PLACE_IN_ORDER';
export const RECEIVE_PLACE_IN_ORDER_DATA = 'RECEIVE_PLACE_IN_ORDER_DATA';
export const RECEIVE_PLACED_ORDERS_RESULTS = 'RECEIVE_PLACED_ORDERS_RESULTS';
export const CLEAR_PLACE_IN_ORDER_DATA = 'CLEAR_PLACE_IN_ORDER_DATA';

export const GET_QUANTITY_DISCOUNT = 'GET_QUANTITY_DISCOUNT';
export const RECEIVE_QUANTITY_DISCOUNT = 'RECEIVE_QUANTITY_DISCOUNT';

export const RECEIVE_ADD_PRODUCTS_TRANS = 'RECEIVE_ADD_PRODUCTS_TRANS';
export const ADD_PRODUCTS_TRANS = 'ADD_PRODUCTS_TRANS';

export const GET_MARKET_ANALYSIS = 'GET_MARKET_ANALYSIS';
export const RECEIVE_MARKET_ANALYSIS = 'RECEIVE_MARKET_ANALYSIS';

export const GET_SINGLE_MARKET_ANALYSIS = 'GET_SINGLE_MARKET_ANALYSIS';
export const RECEIVE_SINGLE_MARKET_ANALYSIS = 'RECEIVE_SINGLE_MARKET_ANALYSIS';

export const GET_PRODUCT_FROM_ANALYSIS = 'GET_PRODUCT_FROM_ANALYSIS';
